### ISSUE TITLE
Export Dialog Is visable

### ISSUE THREAD

**Issue by toddgeist** [rwu2359/CalPick#1]
so neat trick exporting the results to a temp file.  But the export dialog is visible for a brief flash.

Also very complicated

Wouldn't it be much easier to, set a global, and use a script to Get the global?

Todd

**Comment by rwu2359** [comment]
@toddgeist Then you need it on the Relationship Graph?? Was trying to make it as easy to use/integrate as possible....
And avoiding fmp URL too...

Suggestions?

**Comment by toddgeist** [comment]
no you don't.  Just use a script to get the result back

see this
[CalPick-master-tg.zip](https://github.com/rwu2359/CalPick/files/1042159/CalPick-master-tg.zip)

**Comment by rwu2359** [comment]
ONLY just behind you....

new version in a minute or so.

**Comment by rwu2359** [comment]
v1.1 fixes..
